version: '3.8'

services:
  api:
    build: .
    container_name: votacao-api
    ports:
      - "8080:8080"
    environment:
      - API_BASE_URL=${API_BASE_URL:-http://localhost:8080/v1}
      - API_CPF_REAL_URL=https://user-info.herokuapp.com/users
      - API_CPF_MOCK_URL=http://wiremock:8080/users
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/votacao_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres
      - wiremock
  postgres:
    image: postgres:15-alpine
    container_name: votacao-db
    environment:
      POSTGRES_DB: votacao_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  wiremock:
    image: wiremock/wiremock:3.5.2
    container_name: votacao-wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock
