server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/votacao_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

api:
  base-url: "http://localhost:8080/v1"
  real-url: ${API_CPF_REAL_URL:https://user-info.herokuapp.com/users}
  mock-url: ${API_CPF_MOCK_URL:http://localhost:8081/users}